# My K-Means Implementation

    1. Notes for K-Means
    2. My implementation from scratch and using library

## 1. Notes for K-Means
    A. Main idea
    B. How it works
    C. When to use it?

### A. Main idea

K-Means is an unsupervised Machine Learning algorithm. It finds patterns in the input features and groups the data into clusters. Based on the mean position of data points (centroids), it assigns each point to the nearest cluster.

### B. How it works


---

1. Choose the number of clusters
We decide on a parameter **k** (number of clusters). 

---

2. Initialize centroids
Randomly choose **k** points from the dataset (or random positions in feature space, even if these points do not exist in the dataset) as the initial **centroids**.

→ **Centroids** are points representing the center of the cluster.

---

3. Assign points to clusters
For each data point \(x_i\), assign it to the closest centroid using **Euclidean distance**:

$$
d(x_i, \mu_j) = \sqrt{ \sum_{f=1}^{n} \left( x_{i,f} - \mu_{j,f} \right)^2 }
$$

where:
- x_{i,f} - our (i)th data point of (f)th feature 
- \(u{j,f}\) – our (j)th randomly selected centroid of (f)th feature 

-> our model iterates through every feature, because we can not perform calculation between diffrent features and diffrent points.

The cluster assignment is:

$$
c_i = \arg \min_{j \in \{1, \dots, k\}} d(x_i, \mu_j)
$$

---

4. Update centroids
After all points are assigned, compute new centroids by taking the mean of all points in each cluster:

$$
\mu_j = \frac{1}{|C_j|} \sum_{x_i \in C_j} x_i
$$

where:
- (C_j) is the set of points assigned to cluster j
  
---

5. Repeat steps 3–4
Reassign points and update centroids until:
- The centroids do not change significantly  
- Or a maximum number of iterations is reached  

---

6. Objective Function (to minimize)
K-Means minimizes the **within-cluster sum of squares (WCSS):**

$$
J = \sum_{j=1}^{k} \sum_{x_i \in C_j} \| x_i - \mu_j \|^2
$$

This is the measure of how "tight" the clusters are around their centroids.

---


### C. When to use it?


🥳 *K-Means is a good choice when:*

- You want to **discover hidden structure** in unlabeled data.  
- You expect the data to form **roughly spherical clusters** of similar size.  
- You need a **fast and scalable algorithm** (K-Means is computationally efficient).  
- The number of clusters \(k\) is known (or you can estimate it with methods like the **Elbow Method** or **Silhouette Score**).  
- You work with data in **low to medium dimensions** (works best when not too many features).  



*When to Be Careful?* 👾

- If clusters are **not spherical** (e.g., elongated or complex shapes), K-Means may perform poorly.  
- If clusters have **very different sizes or densities**, results may be misleading.  
- Sensitive to **outliers**, since they can pull the centroid far away.  
- Sensitive to **initialization** – different random seeds may give different results.  
  - Solution: use **K-Means++ initialization**.  
- In **high-dimensional space** (curse of dimensionality), distances lose meaning and clustering quality degrades.


-> spherical clusters are desired because of it's distribution near the center!
  if clusters are not this way, use: **DBSCAN** or **Spectral Clustering**  



## 2. My implementation from scratch and using library

In [100]:
# Importing libraries

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from kmeans_model import My_Kmeans
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_mutual_info_score, normalized_mutual_info_score, fowlkes_mallows_score


In [101]:
# Loading data from sklearn load_iris 
iris = load_iris()
X, y = iris.data, iris.target

# Splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=123)

print(y_train)

[2 2 0 0 1 1 2 0 0 1 1 0 2 2 2 2 2 1 0 0 2 0 0 1 1 1 1 2 1 2 0 2 1 0 0 2 1
 2 2 0 1 1 2 0 2 1 1 0 2 2 0 0 1 1 2 0 0 1 0 1 2 0 2 0 0 1 0 0 1 2 1 1 1 0
 0 1 2 0 0 1 1 1 2 1 1 1 2 0 0 1 2 2 2 2 0 1 0 1 1 0 1 2 1 2 2 0 1 0 2 2 1
 1 2 2 1 0 1 1 2 2]


In [102]:
# k -> Number of Clusters
k = 3

# Importing and using my implementation of K-Means Algorithm
model_1 = My_Kmeans()
model_1.fit(X_train, 3)

Clustering for 0th iteration: ['0th: 45', '1th: 13', '2th: 62']
New position after 0th iteration: [[5.31 2.75 3.29 0.97]
 [5.68 3.75 2.83 0.99]
 [6.31 3.1  4.41 1.46]]
---------------------------------------------
Clustering for 5th iteration: ['0th: 34', '1th: 37', '2th: 49']
New position after 5th iteration: [[5.71 2.67 4.1  1.27]
 [5.02 3.43 1.47 0.26]
 [6.62 3.   5.41 1.92]]
---------------------------------------------
Clustering for 10th iteration: ['0th: 43', '1th: 37', '2th: 40']
New position after 10th iteration: [[5.83 2.73 4.23 1.34]
 [5.02 3.43 1.47 0.26]
 [6.7  3.01 5.56 1.99]]
---------------------------------------------
Clustering for 15th iteration: ['0th: 49', '1th: 37', '2th: 34']
New position after 15th iteration: [[5.87 2.74 4.32 1.39]
 [5.02 3.43 1.47 0.26]
 [6.79 3.05 5.67 2.04]]
---------------------------------------------
Clustering for 20th iteration: ['0th: 50', '1th: 37', '2th: 33']
New position after 20th iteration: [[5.88 2.74 4.33 1.4 ]
 [5.02 3.43 1.47 

Because of unsupervised algorithm, to chceck how our model acts on a new data, we need to use diffrent metrics methods than usually.

In [ ]:
y_train_pred = model_1.k

# Changing from dict to segregated list by points, as is in X_train
ordered_labels = []
for x in X_train:
    found = False
    for cluster_id, points in y_train_pred.items():
        if any(np.array_equal(x, p) for p in points):
            cluster_id = int(cluster_id[0:1])
            ordered_labels.append(cluster_id)
            found = True
            break
    if not found:
        ordered_labels.append(None)

# Checking how well our model works
ari = adjusted_mutual_info_score(y_train, ordered_labels)
print(f'Adjusted mutual info score: {round(ari,2)* 100} %')

nmi = normalized_mutual_info_score(y_train, ordered_labels)
print(f'Normalized mutual info score: {round(nmi,2)* 100} %')

fmi = fowlkes_mallows_score(y_train, ordered_labels)
print(f'Fowlkes mallows score: {round(fmi,2)* 100} %')


Adjusted mutual info score: 74.0 %
Normalized mutual info score: 75.0 %
Fowlkes mallows score: 82.0 %



    -> ARI - checks how well predicted clasters matches with real classes

    -> NMI - checks how simillar two clasters are

    -> FMI - checks compliance of range for each point

In [104]:
model_2 = KMeans(n_clusters=3, random_state=123)
y_sklearn_pred = model_2.fit_predict(X_train)

y_sklearn_pred
ari = adjusted_mutual_info_score(y_train, y_sklearn_pred)
print(f'Adjusted mutual info score: {round(ari,2)* 100} %')

nmi = normalized_mutual_info_score(y_train, y_sklearn_pred)
print(f'Normalized mutual info score: {round(nmi,2)* 100} %')

fmi = fowlkes_mallows_score(y_train, y_sklearn_pred)
print(f'Fowlkes mallows score: {round(fmi,2)* 100} %')

Adjusted mutual info score: 73.0 %
Normalized mutual info score: 74.0 %
Fowlkes mallows score: 81.0 %


# Clustering Evaluation Metrics

When evaluating clustering algorithms such as **K-Means**, we often need to compare the predicted clusters with the **true labels** (ground truth).  
Since cluster labels can be permuted (e.g., cluster "0" may correspond to class "virginica"), we use special metrics that are invariant to label permutation.

---

## 1. Adjusted Rand Index (ARI)

The **Rand Index (RI)** measures similarity between two clusterings by counting pairs of points that are:
- in the same cluster in both labelings, or
- in different clusters in both labelings.

Formally, for all pairs of samples:

- \(a\): pairs in the same cluster in both partitions  
- \(b\): pairs in different clusters in both partitions  
- \(c\): pairs in the same cluster in first but different in second  
- \(d\): pairs in different clusters in first but same in second  

The **Rand Index** is:

$$
RI = \frac{a + b}{a + b + c + d}
$$

However, RI does not account for random labeling.  
Therefore, the **Adjusted Rand Index (ARI)** corrects for chance:

$$
ARI = \frac{RI - \mathbb{E}[RI]}{\max(RI) - \mathbb{E}[RI]}
$$

- Range: \([-1, 1]\)  
- \(1\) → perfect agreement  
- Around \(0\) → random labeling  
- Negative values → worse than random  

---

## 2. Normalized Mutual Information (NMI)

Mutual Information (MI) comes from information theory – it measures how much knowing one clustering reduces uncertainty about the other.  

Given clusterings \(U\) and \(V\):

$$
MI(U, V) = \sum_{i=1}^{|U|} \sum_{j=1}^{|V|} 
\frac{|U_i \cap V_j|}{N} \, \log \left( \frac{N \cdot |U_i \cap V_j|}{|U_i| \cdot |V_j|} \right)
$$

where:
- \(N\) – total number of samples  
- \(|U_i|\) – number of points in cluster \(i\) in partition \(U\)  
- \(|V_j|\) – number of points in cluster \(j\) in partition \(V\)  

To normalize between 0 and 1, we use:

$$
NMI(U, V) = \frac{MI(U, V)}{\sqrt{H(U) \cdot H(V)}}
$$

where \(H(U)\), \(H(V)\) are the entropies of the partitions.  

- Range: \([0, 1]\)  
- \(1\) → perfect agreement  
- \(0\) → completely independent clusterings  

---

## 3. Fowlkes-Mallows Index (FMI)

The **FMI** is based on precision and recall for clustering pairs.  

- **TP (True Positive):** pairs in the same cluster in both partitions  
- **FP (False Positive):** pairs in same cluster in predicted, different in true  
- **FN (False Negative):** pairs in different cluster in predicted, same in true  

The formula is:

$$
FMI = \sqrt{ \frac{TP}{TP + FP} \cdot \frac{TP}{TP + FN} }
$$

- Range: \([0, 1]\)  
- \(1\) → perfect clustering  
- Values closer to 0 → poor clustering  

---

## Summary

| Metric | Range | Interpretation |
|--------|-------|----------------|
| **ARI** | \([-1, 1]\) | 1 = perfect, 0 = random, <0 = worse than random |
| **NMI** | \([0, 1]\)  | 1 = perfect, 0 = independent |
| **FMI** | \([0, 1]\)  | 1 = perfect, 0 = poor clustering |

---

## Practical Notes
- All three metrics are **invariant to label permutation** (cluster 0 vs 1 naming does not matter).  
- **ARI** adjusts for chance and can go below 0.  
- **NMI** is based on information theory and is useful for comparing different numbers of clusters.  
- **FMI** focuses on pairwise precision/recall balance.  

